Update AWS Example guide
stateful/vscode-runme pull request #1269
Opened 2024-04-11 16:06 UTC by degrammer

This PRs introduces a more comprehensive guide around using AWS CLI with Runme Notebooks and Cloud renderers for EC2.

2024-04-12 13:31 UTC, sourishkrout commented
@joseeantonior please do a review on the language etc, thanks!

2024-04-12 16:22 UTC, joseeantonior requested changes
Please review and address - let me know when it's ready for another pass.

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +💡 **Important!** Be sure to run through the on-time guide [Getting started with Runme Noteboks for AWS](setup.md).
Are we intending to say "run through the on-time guide first"?

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +One of the fundamental tasks in working with EC2 is to list your instances, serving as the foundation for other operations such as managing instance states—starting, stopping, rebooting, or terminati
Leave a space with the hyphen: "instance states - starting"

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +One of the fundamental tasks in working with EC2 is to list your instances, serving as the foundation for other operations such as managing instance states—starting, stopping, rebooting, or terminati
Same with "terminating them - or securely"

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +Experience it firsthand by running the following URL to see Runme in action!
I'd say finish the sentence with a colon rather than an exclamation mark would be more appropriate.

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +Isn't that cool ? that's a **Runme cloud renderer** in Action!
There's an extra space after cool and before the question mark.

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/ec2.md
> +Now you have the instance configured, run the following command to connect:
Now *that* you have the instance configured

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/setup.md
> +For unix based systems (macOS and Linux), you can use `Homebrew` to install `awscli`.
"For UNIX based systems"

UNIX is a proper name, let's keep it as is

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/setup.md
> +To display profile details, including access key, secret key, and region configuration information utilized for a specified profile, execute the following commands:
"utilized for a specific profile"

2024-04-12 16:22 UTC, joseeantonior commented on examples/aws/setup.md
> +If you haven't configured a profile yet, you can create a default profile by running the following command (ensure you have your Access Key ID and Secret Access Key at hand):
"If you haven't configured a profile yet, you can create a default one by running"

Whatever is in the parenthesis, let's add as a new sentence, as it's information that is relevant to the guide.

2024-04-12 16:59 UTC, joseeantonior approved these changes

2024-04-17 14:55 UTC, sourishkrout approved these changes
👍 LGTM

2024-04-17 14:55 UTC, merged