Update extension README file
stateful/vscode-runme pull request #1270
Opened 2024-04-11 22:15 UTC by degrammer

2024-04-15 21:09 UTC, sourishkrout commented
@joseeantonior can you please go ahead and do a general content/lang review please?

2024-04-17 16:25 UTC, joseeantonior requested changes

2024-04-17 16:25 UTC, joseeantonior commented on README.md
>  RUNME does not just retain frontmatter, it supports top-level settings that will affect all cells in the document.
RUNME or Runme?

2024-04-18 22:33 UTC, sourishkrout commented on README.md
> +runme:
@degrammer remove frontmatter please

2024-04-18 22:34 UTC, sourishkrout requested changes
No frontmatter in this file please (it's going on the MSFT marketplace). Otherwise 👍.

2024-04-19 12:08 UTC, sourishkrout approved these changes
👍 LGTM

2024-04-19 12:08 UTC, merged