Update GCP examples
stateful/vscode-runme pull request #1284
Opened 2024-04-17 04:06 UTC by degrammer

Update GCP examples, includes setup, GKE and GCE.

2024-04-17 16:29 UTC, joseeantonior requested changes

2024-04-17 16:29 UTC, joseeantonior commented on examples/gcp/gce.md
> +Google Compute Engine (also known as GCE) enables users to launch virtual machines on demand, it supports different operating systems like Linux, FreeBSD, NetBSD and Windows.
"on demand. It supports"

2024-04-17 16:29 UTC, joseeantonior commented on examples/gcp/gce.md
> +With GCE, you can deploy Web and App servers, containerized microservices, virtual desktops, Databases, etc.
"virtual desktops, databases, and more."

2024-04-18 22:27 UTC, sourishkrout approved these changes
👍 LGTM

2024-04-19 15:58 UTC, merged