Initial work replace RunmeLauncherProvider
stateful/vscode-runme pull request #1730
Opened 2024-10-15 15:24 UTC by pastuxso

This approach is looking forward to re-using the same source to provide a list of Tasks.

2024-10-18 22:18 UTC, sourishkrout commented
where's the icon @pastuxso?

<img width="542" alt="image" src="https://github.com/user-attachments/assets/a9efffa3-d01f-4fae-97f4-8ae4bf3465db">

2024-10-18 22:48 UTC, pastuxso commented
@sourishkrout Icon added. I don't know why it was ignored.

2024-10-21 18:43 UTC, sourishkrout requested changes
The unnamed tasks visibility default must match the legacy launcher to merge this first version.

The performance impacts of not using the vscode APIs can be addressed in separate PRs—however, there will be no public release until these are solved.

2024-10-21 18:43 UTC, sourishkrout commented on src/extension/provider/launcherBeta.ts
> +    this.tasks = lastValueFrom(this.loadProjectTasks())
why duplicate the work the task loader's already done?

2024-10-21 18:43 UTC, sourishkrout commented on src/extension/provider/launcherBeta.ts
> +  private allowUnnamed = true
Unnamed tasks clutter. Why not `false` like the old default?

2024-10-21 18:43 UTC, sourishkrout commented on src/extension/provider/launcherBeta.ts
> +        notebook = from(this.serializer.deserializeNotebook(mdBuffer, token))
Again, why duplicate the work the task loader's already done? it's expensive to traverse plus deserialize files in a project/repo multiple times

2024-10-21 18:43 UTC, sourishkrout commented on src/extension/provider/launcherBeta.ts
> +    this.tasks = lastValueFrom(this.loadProjectTasks())
isn't this what the vscode API `tasks.fetchTasks({ type: 'runme' })` is for?

2024-10-25 18:22 UTC, sourishkrout commented
I am merging this with the correct default. Please address the remaining comments in separate issues/tickets when we pick this up again, @pastuxso.

2024-10-25 18:22 UTC, merged

2024-10-25 18:23 UTC, pastuxso commented
@sourishkrout no problem. Go ahead.

2024-11-07 16:38 UTC, pastuxso commented
Work in progress https://github.com/stateful/vscode-runme/pull/1784