Fix notebook terminal resizing
stateful/vscode-runme pull request #373
Opened 2023-04-03 18:29 UTC by mxsdev

I don't think it's necessary to cache position to ensure not running fit, since it needs to be run every resize anyway.

This PR will be needed for implementing terminal (PTY) resizing.

2023-04-03 18:31 UTC, sourishkrout commented
Good point! I forgot to add this to the roadmap item

2023-04-04 12:57 UTC, sourishkrout requested changes
Are integrated and notebook terminals competing here? Something seems off.

https://user-images.githubusercontent.com/250527/229798887-1e834f1a-8e4e-4596-8d0c-93f939c15d07.mp4

2023-04-04 17:59 UTC, mxsdev commented
@sourishkrout 

This PR is not for PTY resizing. Rather, it is a prerequisite for PTY resizing. Sorry if my language was ambiguous.

This PR is about resizing VSCode's window. It allows for word wrapping in this case, and for the notebook terminal itself to change size as a result. PTY resizing is for a follow-up PR.

2023-04-04 20:29 UTC, sourishkrout approved these changes
Sounds like you have a plan @mxsdev.

2023-04-04 20:47 UTC, merged