cell config visual update, add docs
stateful/vscode-runme pull request #655
Opened 2023-07-04 07:04 UTC by admc

2023-07-04 07:07 UTC, admc commented
@christian-bromann can you do a review and help me QA this. Some new tech here for me so point out anything learning worthy please. I also see some errors in the console log related to the kernel and I don't know what they mean.

2023-07-05 16:45 UTC, admc commented
Doesn't yet have links to everything, but there are tickets for those docs: 

- https://github.com/stateful/docs.runme.dev/issues/186
- https://github.com/stateful/docs.runme.dev/issues/185

<img width="1023" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/87838c49-4f6c-45b2-8012-a70b58cbb807">
<img width="995" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/177bbb0f-eb9e-4ab7-9eef-fcf5a6c4e90f">
<img width="1007" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/6682b86a-037d-4921-a12d-9823df9faecd">

2023-07-05 17:26 UTC, christian-bromann reviewed
Overall looks good to me, all works well. Some suggestions on some code parts and naming.

2023-07-05 17:26 UTC, christian-bromann commented on src/client/components/configuration/annotations.ts
> +    const details = this.#details?.[id] as any
```suggestion
  renderCheckboxTabEntry(id: AnnotationsKey) {
    const value = this.annotations?.[id]
    const details = this.#details?.[id]
```

2023-07-05 17:26 UTC, christian-bromann commented on src/client/components/configuration/annotations.ts
> +    const details = this.#details?.[id] as any
```suggestion
  renderTextFieldTabEntry(id: AnnotationsKey) {
    const value = this.annotations?.[id]
    const details = this.#details?.[id]
```

2023-07-05 17:26 UTC, christian-bromann commented on src/client/components/configuration/annotations.ts
> +    const details = this.#details?.[id] as any
```suggestion
  renderCategoryTabEntry(id: AnnotationsKey) {
    const value = this.annotations?.[id]
    const details = this.#details?.[id]
```

2023-07-05 17:29 UTC, christian-bromann commented
> Doesn't yet have links to everything, but there are tickets for those docs:

Working on them now.

2023-07-05 20:46 UTC, christian-bromann commented
> Working on them now.

There are PRs for both of them now:

- https://github.com/stateful/docs.runme.dev/pull/187
- https://github.com/stateful/docs.runme.dev/pull/188

2023-07-06 12:03 UTC, admc commented on src/client/components/configuration/annotations.ts
> +      <vscode-panels>
So to be clear, you would use local storage to store the last selected tab of any cell and continue using that until they changed it? I wonder if that is desired behavior, if I open config on one cell and goto advanced, and then I goto a different cell to configure it, I think i'd be expecting to see general?

2023-07-06 12:04 UTC, admc commented on src/client/components/configuration/annotations.ts
> +      </div>
Moved it into a function, all cells must have docs.

2023-07-06 12:05 UTC, admc commented on src/client/components/configuration/annotations.ts
> +          <vscode-link href="${details.docs}">(docs)</vscode-link>
I'd prefer the icon, but using vscode codicon and product icons, I can't get it to render and I dont want to bring custom icons in, as we know they are already part of vs code. Maybe you can help me figure out how to use those icons in the "web" view here. Maybe @degrammer knows something about this?

- https://code.visualstudio.com/api/references/icons-in-labels
- https://github.com/microsoft/vscode-codicons

2023-07-06 18:38 UTC, christian-bromann commented on src/client/components/configuration/annotations.ts
> +      <vscode-panels>
I was seeing it from the perspective of changing a particular configuration (e.g. cell name) that is not in the 1st panel. In this situation I would always have to switch to that panel which can be sub optimal in the experience. However this seems to be something we can find out through user feedback.

2023-07-06 18:47 UTC, sourishkrout commented
Looks great overall. In the light theme, though, the headlines are difficult to read:

<img width="2039" alt="image" src="https://github.com/stateful/vscode-runme/assets/250527/4ee60935-54b7-4587-811d-0defce087a0e">

2023-07-06 18:48 UTC, sourishkrout requested changes
See comment.

2023-07-06 18:57 UTC, admc commented
Oh gosh, totally meant to update to the css variables, woopsy, nice catch.

2023-07-06 22:26 UTC, admc commented
The tab underlines are still a bit light for the light themes, but that will require some more css digging to fix.

<img width="1102" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/b3a8ec4f-6558-487f-bf71-962155e3f435">

2023-07-06 22:28 UTC, admc commented
@sourishkrout give that a try when you have a min.

2023-07-07 13:19 UTC, degrammer commented on src/client/components/configuration/annotations.ts
> +          <vscode-link href="${details.docs}">(docs)</vscode-link>
@admc Right now we don't have support for vscode icons, we may want to explore adding support to it, meanwhile what we're doing is to define the Icon SVG directly here https://github.com/stateful/vscode-runme/tree/main/src/client/components/icons

2023-07-07 14:07 UTC, sourishkrout approved these changes
Works 👍 . The underlying of the tab header is good enough for now. Shouldn't hold up a merge.

2023-07-07 17:34 UTC, merged